@server=http://localhost:4004
@username=alice
@password=


### Users
# @name Users_GET
GET {{server}}/odata/v4/restaurant/Users
Authorization: Basic {{username}}:{{password}}


### Users
# @name Users_POST
POST {{server}}/odata/v4/restaurant/Users
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "30578040-26c9-4d35-ae93-544567f3cb82",
  "name": "name-30578040",
  "email": "email-30578040",
  "number": "r-30578040",
  "type": "Customer",
  "Address": {
    "ID": "25928986-9572-49fc-adaa-bfde6821bb50"
  }
}


### Users
# @name Users_PATCH
PATCH {{server}}/odata/v4/restaurant/Users/30578040-26c9-4d35-ae93-544567f3cb82
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "30578040-26c9-4d35-ae93-544567f3cb82",
  "name": "name-30578040",
  "email": "email-30578040",
  "number": "r-30578040",
  "type": "Customer",
  "Address": {
    "ID": "25928986-9572-49fc-adaa-bfde6821bb50"
  }
}


### Users
# @name Users_DELETE
DELETE {{server}}/odata/v4/restaurant/Users/30578040-26c9-4d35-ae93-544567f3cb82
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Addresses
# @name Addresses_GET
GET {{server}}/odata/v4/restaurant/Addresses
Authorization: Basic {{username}}:{{password}}


### Addresses
# @name Addresses_POST
POST {{server}}/odata/v4/restaurant/Addresses
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "25928986-9572-49fc-adaa-bfde6821bb50",
  "addressLine1": "addressLine1-25928986",
  "addressLine2": "addressLine2-25928986",
  "city": "city-25928986",
  "stateProvince": "stateProvince-25928986",
  "postalCode": "postalCode-25928986"
}


### Addresses
# @name Addresses_PATCH
PATCH {{server}}/odata/v4/restaurant/Addresses/25928986-9572-49fc-adaa-bfde6821bb50
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "25928986-9572-49fc-adaa-bfde6821bb50",
  "addressLine1": "addressLine1-25928986",
  "addressLine2": "addressLine2-25928986",
  "city": "city-25928986",
  "stateProvince": "stateProvince-25928986",
  "postalCode": "postalCode-25928986"
}


### Addresses
# @name Addresses_DELETE
DELETE {{server}}/odata/v4/restaurant/Addresses/25928986-9572-49fc-adaa-bfde6821bb50
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Restaurants
# @name Restaurants_GET
GET {{server}}/odata/v4/restaurant/Restaurants
Authorization: Basic {{username}}:{{password}}


### Restaurants
# @name Restaurants_POST
POST {{server}}/odata/v4/restaurant/Restaurants
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "29549611-057e-44b9-bfc1-5ed4f8e4f3b4",
  "name": "name-2954961",
  "description": "description-2954961",
  "cuisine": "cuisine-2954961",
  "Address": {
    "ID": "25928986-9572-49fc-adaa-bfde6821bb50"
  },
  "menu": [
    {
      "ID": "68938195-b4ce-48ee-b410-196beb3f3b41",
      "name": "name-6893819",
      "description": "description-6893819",
      "price": 55796824.68,
      "image": "image-6893819",
      "itmes": [
        {
          "ID": "21983203-6cfa-495b-beaa-6d2edccc6107",
          "name": "name-21983203",
          "description": "description-21983203",
          "price": 91267386.05,
          "isAvailable": false,
          "imageUrl": "imageUrl-21983203",
          "createdAt": "2022-09-16T00:00:00.000Z",
          "createdBy": "createdBy.d36cj@example.org",
          "modifiedAt": "2016-10-22T00:00:00.000Z",
          "modifiedBy": "modifiedBy.d36cj@example.com"
        },
        {
          "ID": "21983204-3d66-4685-81ff-aa36ba97aa75",
          "name": "name-21983204",
          "description": "description-21983204",
          "price": 66779005.21,
          "isAvailable": true,
          "imageUrl": "imageUrl-21983204",
          "createdAt": "2012-11-09T00:00:00.000Z",
          "createdBy": "createdBy.d36ck@example.org",
          "modifiedAt": "2003-02-08T00:00:00.000Z",
          "modifiedBy": "modifiedBy.d36ck@example.net"
        }
      ],
      "createdAt": "2015-10-27T00:00:00.000Z",
      "createdBy": "createdBy.43raz@example.net",
      "modifiedAt": "2010-01-23T00:00:00.000Z",
      "modifiedBy": "modifiedBy.43raz@example.com"
    },
    {
      "ID": "6893820a-7630-4606-9b9b-1fd2e09e82b0",
      "name": "name-6893820",
      "description": "description-6893820",
      "price": 69798161.68,
      "image": "image-6893820",
      "itmes": [
        {
          "ID": "19715447-5129-4382-ad32-5c28a3a92253",
          "name": "name-19715447",
          "description": "description-19715447",
          "price": 71950928.96,
          "isAvailable": false,
          "imageUrl": "imageUrl-19715447",
          "createdAt": "2015-12-09T00:00:00.000Z",
          "createdBy": "createdBy.bqkjb@example.org",
          "modifiedAt": "2014-07-13T00:00:00.000Z",
          "modifiedBy": "modifiedBy.bqkjb@example.org"
        },
        {
          "ID": "19715448-3d1e-42be-8281-7ae9b63b1fc9",
          "name": "name-19715448",
          "description": "description-19715448",
          "price": 41170239.04,
          "isAvailable": true,
          "imageUrl": "imageUrl-19715448",
          "createdAt": "2012-02-21T00:00:00.000Z",
          "createdBy": "createdBy.bqkjc@example.org",
          "modifiedAt": "2002-07-13T00:00:00.000Z",
          "modifiedBy": "modifiedBy.bqkjc@example.com"
        }
      ],
      "createdAt": "2012-06-25T00:00:00.000Z",
      "createdBy": "createdBy.43rb0@example.org",
      "modifiedAt": "2000-09-17T00:00:00.000Z",
      "modifiedBy": "modifiedBy.43rb0@example.com"
    }
  ]
}


### Restaurants
# @name Restaurants_PATCH
PATCH {{server}}/odata/v4/restaurant/Restaurants/29549611-057e-44b9-bfc1-5ed4f8e4f3b4
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "29549611-057e-44b9-bfc1-5ed4f8e4f3b4",
  "name": "name-2954961",
  "description": "description-2954961",
  "cuisine": "cuisine-2954961",
  "Address": {
    "ID": "25928986-9572-49fc-adaa-bfde6821bb50"
  },
  "menu": [
    {
      "ID": "68938195-b4ce-48ee-b410-196beb3f3b41",
      "name": "name-6893819",
      "description": "description-6893819",
      "price": 55796824.68,
      "image": "image-6893819",
      "itmes": [
        {
          "ID": "21983203-6cfa-495b-beaa-6d2edccc6107",
          "name": "name-21983203",
          "description": "description-21983203",
          "price": 91267386.05,
          "isAvailable": false,
          "imageUrl": "imageUrl-21983203",
          "createdAt": "2022-09-16T00:00:00.000Z",
          "createdBy": "createdBy.d36cj@example.org",
          "modifiedAt": "2016-10-22T00:00:00.000Z",
          "modifiedBy": "modifiedBy.d36cj@example.com"
        },
        {
          "ID": "21983204-3d66-4685-81ff-aa36ba97aa75",
          "name": "name-21983204",
          "description": "description-21983204",
          "price": 66779005.21,
          "isAvailable": true,
          "imageUrl": "imageUrl-21983204",
          "createdAt": "2012-11-09T00:00:00.000Z",
          "createdBy": "createdBy.d36ck@example.org",
          "modifiedAt": "2003-02-08T00:00:00.000Z",
          "modifiedBy": "modifiedBy.d36ck@example.net"
        }
      ],
      "createdAt": "2015-10-27T00:00:00.000Z",
      "createdBy": "createdBy.43raz@example.net",
      "modifiedAt": "2010-01-23T00:00:00.000Z",
      "modifiedBy": "modifiedBy.43raz@example.com"
    },
    {
      "ID": "6893820a-7630-4606-9b9b-1fd2e09e82b0",
      "name": "name-6893820",
      "description": "description-6893820",
      "price": 69798161.68,
      "image": "image-6893820",
      "itmes": [
        {
          "ID": "19715447-5129-4382-ad32-5c28a3a92253",
          "name": "name-19715447",
          "description": "description-19715447",
          "price": 71950928.96,
          "isAvailable": false,
          "imageUrl": "imageUrl-19715447",
          "createdAt": "2015-12-09T00:00:00.000Z",
          "createdBy": "createdBy.bqkjb@example.org",
          "modifiedAt": "2014-07-13T00:00:00.000Z",
          "modifiedBy": "modifiedBy.bqkjb@example.org"
        },
        {
          "ID": "19715448-3d1e-42be-8281-7ae9b63b1fc9",
          "name": "name-19715448",
          "description": "description-19715448",
          "price": 41170239.04,
          "isAvailable": true,
          "imageUrl": "imageUrl-19715448",
          "createdAt": "2012-02-21T00:00:00.000Z",
          "createdBy": "createdBy.bqkjc@example.org",
          "modifiedAt": "2002-07-13T00:00:00.000Z",
          "modifiedBy": "modifiedBy.bqkjc@example.com"
        }
      ],
      "createdAt": "2012-06-25T00:00:00.000Z",
      "createdBy": "createdBy.43rb0@example.org",
      "modifiedAt": "2000-09-17T00:00:00.000Z",
      "modifiedBy": "modifiedBy.43rb0@example.com"
    }
  ]
}


### Restaurants
# @name Restaurants_DELETE
DELETE {{server}}/odata/v4/restaurant/Restaurants/29549611-057e-44b9-bfc1-5ed4f8e4f3b4
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### MenuItems
# @name MenuItems_GET
GET {{server}}/odata/v4/restaurant/MenuItems
Authorization: Basic {{username}}:{{password}}


### MenuItems
# @name MenuItems_POST
POST {{server}}/odata/v4/restaurant/MenuItems
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "68938195-b4ce-48ee-b410-196beb3f3b41",
  "name": "name-6893819",
  "description": "description-6893819",
  "price": 55796824.68,
  "image": "image-6893819",
  "itmes": [
    {
      "ID": "21983203-6cfa-495b-beaa-6d2edccc6107",
      "name": "name-21983203",
      "description": "description-21983203",
      "price": 91267386.05,
      "isAvailable": false,
      "imageUrl": "imageUrl-21983203",
      "createdAt": "2022-09-16T00:00:00.000Z",
      "createdBy": "createdBy.d36cj@example.org",
      "modifiedAt": "2016-10-22T00:00:00.000Z",
      "modifiedBy": "modifiedBy.d36cj@example.com"
    },
    {
      "ID": "21983204-3d66-4685-81ff-aa36ba97aa75",
      "name": "name-21983204",
      "description": "description-21983204",
      "price": 66779005.21,
      "isAvailable": true,
      "imageUrl": "imageUrl-21983204",
      "createdAt": "2012-11-09T00:00:00.000Z",
      "createdBy": "createdBy.d36ck@example.org",
      "modifiedAt": "2003-02-08T00:00:00.000Z",
      "modifiedBy": "modifiedBy.d36ck@example.net"
    }
  ],
  "createdAt": "2015-10-27T00:00:00.000Z",
  "createdBy": "createdBy.43raz@example.net",
  "modifiedAt": "2010-01-23T00:00:00.000Z",
  "modifiedBy": "modifiedBy.43raz@example.com"
}


### MenuItems
# @name MenuItems_PATCH
PATCH {{server}}/odata/v4/restaurant/MenuItems/68938195-b4ce-48ee-b410-196beb3f3b41
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "68938195-b4ce-48ee-b410-196beb3f3b41",
  "name": "name-6893819",
  "description": "description-6893819",
  "price": 55796824.68,
  "image": "image-6893819",
  "itmes": [
    {
      "ID": "21983203-6cfa-495b-beaa-6d2edccc6107",
      "name": "name-21983203",
      "description": "description-21983203",
      "price": 91267386.05,
      "isAvailable": false,
      "imageUrl": "imageUrl-21983203",
      "createdAt": "2022-09-16T00:00:00.000Z",
      "createdBy": "createdBy.d36cj@example.org",
      "modifiedAt": "2016-10-22T00:00:00.000Z",
      "modifiedBy": "modifiedBy.d36cj@example.com"
    },
    {
      "ID": "21983204-3d66-4685-81ff-aa36ba97aa75",
      "name": "name-21983204",
      "description": "description-21983204",
      "price": 66779005.21,
      "isAvailable": true,
      "imageUrl": "imageUrl-21983204",
      "createdAt": "2012-11-09T00:00:00.000Z",
      "createdBy": "createdBy.d36ck@example.org",
      "modifiedAt": "2003-02-08T00:00:00.000Z",
      "modifiedBy": "modifiedBy.d36ck@example.net"
    }
  ],
  "createdAt": "2015-10-27T00:00:00.000Z",
  "createdBy": "createdBy.43raz@example.net",
  "modifiedAt": "2010-01-23T00:00:00.000Z",
  "modifiedBy": "modifiedBy.43raz@example.com"
}


### MenuItems
# @name MenuItems_DELETE
DELETE {{server}}/odata/v4/restaurant/MenuItems/68938195-b4ce-48ee-b410-196beb3f3b41
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Food
# @name Food_GET
GET {{server}}/odata/v4/restaurant/Food
Authorization: Basic {{username}}:{{password}}


### Food
# @name Food_POST
POST {{server}}/odata/v4/restaurant/Food
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "21983203-6cfa-495b-beaa-6d2edccc6107",
  "name": "name-21983203",
  "description": "description-21983203",
  "price": 91267386.05,
  "isAvailable": false,
  "imageUrl": "imageUrl-21983203",
  "createdAt": "2022-09-16T00:00:00.000Z",
  "createdBy": "createdBy.d36cj@example.org",
  "modifiedAt": "2016-10-22T00:00:00.000Z",
  "modifiedBy": "modifiedBy.d36cj@example.com"
}


### Food
# @name Food_PATCH
PATCH {{server}}/odata/v4/restaurant/Food/21983203-6cfa-495b-beaa-6d2edccc6107
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "21983203-6cfa-495b-beaa-6d2edccc6107",
  "name": "name-21983203",
  "description": "description-21983203",
  "price": 91267386.05,
  "isAvailable": false,
  "imageUrl": "imageUrl-21983203",
  "createdAt": "2022-09-16T00:00:00.000Z",
  "createdBy": "createdBy.d36cj@example.org",
  "modifiedAt": "2016-10-22T00:00:00.000Z",
  "modifiedBy": "modifiedBy.d36cj@example.com"
}


### Food
# @name Food_DELETE
DELETE {{server}}/odata/v4/restaurant/Food/21983203-6cfa-495b-beaa-6d2edccc6107
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### verifyEmail
# @name verifyEmail_POST
POST {{server}}/odata/v4/restaurant/verifyEmail
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "email": "suvm1sahoo@gmail.com"
}


### verifyOtp
# returns { message, attempt, SeasonKey }
# @name verifyOtp_POST
POST {{server}}/odata/v4/restaurant/verifyOtp
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "email": "suvm1sahoo@gmail.com",
  "otp": "9280"
}

# @seasonKey = {{verifyOtp_POST.response.body.SeasonKey}}



### createUser
# returns { message, ID }
# @name createUser_POST
POST {{server}}/odata/v4/restaurant/createUser
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "SeasonKey":"{{verifyOtp_POST.response.body.$.SeasonKey}}",
  "basicDetails": {
    "name": "Subham",
    "email": "suvm1sahoo@gmail.com",
    "number": "9348514583",
    "type": "R"
  },
  "addressDetails": {
    "addressLine1": "addressLine1-17572276",
    "addressLine2": "addressLine2-17572276",
    "city": "city-17572276",
    "stateProvince": "stateProvince-17572276",
    "postalCode": "766100"
  }
}